[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
types = { workspace = true }
gateway = { workspace = true }
tools = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
dotenvy = { workspace = true }
skills = { workspace = true }
