[package]
name = "vc-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
vc-types = { workspace = true }
vc-gateway = { workspace = true }
vc-tools = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
dotenvy = { workspace = true }
